Betgo/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Razor;
using Google.Maps;

namespace Betgo.Models
{
    public class Event
    {
        
        public int Id { get; set; }
        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        [Required]
        public DateTime ActualDateTime { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        //[Required]
        public Competitor CompetitorA { get; set; }
        //[Required]
        public Competitor CompetitorB { get; set; }
        
        public double OddsA { get; set; }
        
        public double OddsB { get; set; }

        public double AWinsReturn { get;  set; }
        public double BWinsReturn { get; set; }
        public EventType Type { get; set; }

        public string Body { get; set; }
        public string ImageLink { get; set; }
        public bool PaidOut { get; set; }
        public bool Winner { get; set; }
        public string Address { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
    }
}

Betgo/Models/EventType.cs
namespace Betgo.Models
{
    public class EventType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Betgo/ViewModels/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Betgo.Models;
using Google.Maps;

namespace Betgo.ViewModels
{
    public class EventViewModel
    {
        [Required]
        public string Name { get; set; }
        [LaterDate]
        [Required]
        public string DateTime { get; set; }
        [Required]
        public int CompA { get; set; }
        [Required]
        public int CompB { get; set; }
        [Required]
        public int Type { get; set; }

        public string ImageLink { get; set; }
        public IEnumerable<EventType> Types { get; set; }
        public IEnumerable<Competitor> Competitors { get; set; }
        public string Address { get; set; }
    }
}

Betgo/Controllers/CompetitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Betgo.Models;
using Betgo.ViewModels;
using System.Data.Entity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Betgo.Controllers
{
    public class CompetitorController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();
        // GET: Competitor
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var viewModel = new CompetitorViewModel
            {
                Types = _context.EventTypes.ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(CompetitorViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Types = _context.EventTypes.ToList();
                return View("Create", viewModel);
            }

            var type = _context.EventTypes.Single(t => t.Id == viewModel.Type);

            _context.Competitors.Add(new Competitor
            {
                Name = viewModel.Name,
                Odds = (double)viewModel.Odds,
                Details = viewModel.Body,
                Type = type,
                ImageLink = viewModel.ImageLink
            });

            _context.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public ActionResult Details(int compId, int eventId)
        {
            var comp = _context.Competitors.Single(c => c.Id == compId);
            var events = _context.Events
                .Include(e => e.CompetitorA)
                .Include(e => e.CompetitorB)
                .Include(e => e.Type)
                .Where(e => e.CompetitorA.Id == compId || e.CompetitorB.Id == compId);
            return View("Details", new CompetitorDetailsViewModel {Competitor = comp, Events = events, EventId = eventId});
        }
    }
}

Betgo/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Betgo.Models;
using Betgo.ViewModels;
using System.Data.Entity;
using Google.Maps;
using Google.Maps.Geocoding;
using Google.Maps.Places;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

namespace Betgo.Controllers
{
    public class EventController : Controller
    {
        private ApplicationDbContext _context;

        public EventController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var viewModel = new EventViewModel
            {
                Types = _context.EventTypes.ToList(),
                Competitors = _context.Competitors.ToList()
            };

            return View(viewModel);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult Create(EventViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Competitors = _context.Competitors.ToList();
                viewModel.Types = _context.EventTypes.ToList();
                return View("Create", viewModel);
            }

            var request = new GeocodingRequest {Address = viewModel.Address, Sensor = false};
            var response = new GeocodingService().GetResponse(request);
            var result = response.Results.First();
            var address = result.FormattedAddress;
            var lon = result.Geometry.Location.Longitude;
            var lat = result.Geometry.Location.Latitude;
            //var placeRequest = new NearbySearchRequest {Radius = 100 ,Location = new LatLng(geoResult.Geometry.Location.Latitude, geoResult.Geometry.Location.Longitude), Sensor = false};
            //var placeResponse = new PlacesService().GetResponse(placeRequest);
            //var address = placeResponse.Results.First().FormattedAddress;

            var dt = DateTime.Parse(viewModel.DateTime);
            var type = _context.EventTypes.Single(t => t.Id == viewModel.Type);
            var compA = _context.Competitors.Single(c => c.Id == viewModel.CompA);
            var compB = _context.Competitors.Single(c => c.Id == viewModel.CompB);
            var newevent = new Event
            {
                CompetitorA = compA,
                CompetitorB = compB,
                Name = viewModel.Name,
                ActualDateTime = dt,
                Date = dt.ToShortDateString(),
                Time = dt.ToShortTimeString(),
                OddsA = compA.Odds,
                OddsB = compB.Odds,
                Type = type,
                AWinsReturn = compB.Odds / compA.Odds + 1,
                BWinsReturn = compA.Odds / compB.Odds + 1,
                ImageLink = viewModel.ImageLink,
                Address = address,
                Long = lon,
                Lat = lat
            };
            _context.Events.Add(newevent);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
            ;
        }

        
        public ActionResult Details(int eventId)
        {
            var events = _context.Events
                .Include(e => e.CompetitorA)
                .Include(e => e.CompetitorB)
                .Single(e => e.Id == eventId);
            return View(new DetailsViewModel(events));
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int eventId)
        {
            var events = _context.Events.Single(e => e.Id == eventId);
            _context.Events.Remove(events);
            var bets = _context.Bets.Where(b => b.EventId == eventId);
            _context.Bets.RemoveRange(bets);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult CompleteEvents()
        {
            var paying = _context.Events
                .Where(e => e.ActualDateTime < new DateTime(2020,01,01))
                .Where(e => e.PaidOut == false);

            //TODO: REAL DATETIME AND AUTOMATING THE CHECK OF ELAPSED EVENTS

            foreach (var events in paying)
            {
                var bets = _context.Bets.Where(b => b.EventId == events.Id);
                foreach (var bet in bets)
                {
                    var user = _context.Users.Single(u => u.Id == bet.UserId);
                    if(events.Winner == bet.ChosenOption) user.Money += bet.ReturnAmount;
                }
                
                events.PaidOut = true;
            }

            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AddWinner(int eventId, bool Winner)
        {
            _context.Events.Single(e => e.Id == eventId).Winner = Winner;
            _context.SaveChanges();

            return RedirectToAction("Details", "Event", new {eventId = eventId});
        }
    }
}

Betgo/Views/Event/Details.cshtml
@model Betgo.ViewModels.DetailsViewModel

@{
    ViewBag.Title = @Model.Name + "- Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />

    <dl class="dl-horizontal">
        @*<h4>@ViewBag.Message</h4>*@
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompetitorA.Name)
        </dt>

        <dd>
            @Html.ActionLink(@Model.CompetitorA.Name,"Details","Competitor",new {compId = Model.CompetitorA.Id, eventId = Model.CurrEvent.Id},null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OddsA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OddsA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompetitorB.Name)
        </dt>

        <dd>
            @Html.ActionLink(@Model.CompetitorB.Name, "Details", "Competitor", new { compId = Model.CompetitorB.Id, eventId = Model.CurrEvent.Id }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OddsB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OddsB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AWinsReturn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AWinsReturn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BWinsReturn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BWinsReturn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        
        @if (Model.CurrEvent.PaidOut && Model.CurrEvent.Winner)
        {
            <dt>
                @Html.DisplayName("Winner")
            </dt>

            <dd>
                @Html.ActionLink(@Model.CompetitorB.Name, "Details", "Competitor", new { compId = Model.CompetitorB.Id, eventId = Model.CurrEvent.Id }, null)
            </dd>
        }
        
        else if (Model.CurrEvent.PaidOut && !Model.CurrEvent.Winner)
        {
            <dt>
                @Html.DisplayName("Winner")
            </dt>

            <dd>
                @Html.ActionLink(@Model.CompetitorA.Name, "Details", "Competitor", new { compId = Model.CompetitorA.Id, eventId = Model.CurrEvent.Id }, null)
            </dd>
        }
    </dl>
</div>
<div id="map"></div>
<hr/>
@if (User.IsInRole("Administrator"))
{
    @Html.ActionLink("Delete event","Delete","Event",new {eventId = Model.CurrEvent.Id},null)
}

<p>
    @if (Request.IsAuthenticated)
    {
        @Html.Partial("_BetPartial", @Model.betViewModel)
        <br/>
        <br/>
        if (User.IsInRole("Administrator") && Model.CurrEvent.PaidOut == false)
        {
            using (Html.BeginForm("AddWinner", "Event", new {eventId = Model.CurrEvent.Id}, FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
            {

                <div class="container">

                    <h2>The winner:</h2>

                    <ul>
                        @Html.RadioButtonFor(model => model.Winner, Model.Winner) @Model.CurrEvent.CompetitorA.Name
                        @Html.RadioButtonFor(model => model.Winner, !Model.Winner) @Model.CurrEvent.CompetitorB.Name

                    </ul>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Add winner"/>
                    </div>
                </div>
            }
        }
    }
    else
    {
        @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
        @: or 
        @Html.ActionLink("Log in", "Login", "Account", null, htmlAttributes: new { id = "loginLink" })
        @: to place a bet!
    }
    <br />
    <br/>
    @Html.ActionLink("Back to List", "Index", "Home")
</p>

<script>
    function initMap() {
        var uluru = { lat: @Model.Lat, lng: @Model.Long };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDA09HtxMyLXyARlycNpb9T76Sl7oEAmQo&callback=initMap">
</script>